from pulp import LpVariable, lpSum

class MinCoreUsage():
    def min_core_usage(self, assigned, cores, tasks_instances, prob):
        # Variable to track if a core is being used. (u_j)
        unused = LpVariable.dicts("u", ((core['name']) for core in cores), 
                             lowBound=0, upBound=1, cat='Binary')
                   
        # 5. If a task instance uses a core, the core is marked used. (Generated by ChatGPT) (From C1111 - C1144)
        for core in cores:
            for task in tasks_instances:
                prob += assigned[(task['name'], core['name'])] <= unused[(core['name'])]

        objective = lpSum(unused[(core['name'])] for core in cores)
        prob += objective, "Minimise Core Usage" 
